--      Team 1: Map Ids in the range 101

INSERT INTO `maps` (`Id`, `Name`, `Image`, `Thumb`, `Width`, `Height`) VALUES ('101', 'Team 1 LeedsMap2', 'Team1map2.png', 'Team1map2Thumb.png', '748', '747');

-- 2. The locations on the map. MapId MUST match the Id above.

INSERT INTO `locations` (`MapId`, `Number`, `xPos`, `yPos`) VALUES ('101', '1', '283', '391');
INSERT INTO `locations` (`MapId`, `Number`, `xPos`, `yPos`) VALUES ('101', '2', '337', '553');
INSERT INTO `locations` (`MapId`, `Number`, `xPos`, `yPos`) VALUES ('101', '3', '335', '627');
INSERT INTO `locations` (`MapId`, `Number`, `xPos`, `yPos`) VALUES ('101', '4', '213', '602');
INSERT INTO `locations` (`MapId`, `Number`, `xPos`, `yPos`) VALUES ('101', '5', '158', '632');
INSERT INTO `locations` (`MapId`, `Number`, `xPos`, `yPos`) VALUES ('101', '6', '86', '600');
INSERT INTO `locations` (`MapId`, `Number`, `xPos`, `yPos`) VALUES ('101', '7', '158', '490');
INSERT INTO `locations` (`MapId`, `Number`, `xPos`, `yPos`) VALUES ('101', '8', '167', '340');
INSERT INTO `locations` (`MapId`, `Number`, `xPos`, `yPos`) VALUES ('101', '9', '158', '391');
INSERT INTO `locations` (`MapId`, `Number`, `xPos`, `yPos`) VALUES ('101', '10', '68', '421');
INSERT INTO `locations` (`MapId`, `Number`, `xPos`, `yPos`) VALUES ('101', '11', '408', '392');
INSERT INTO `locations` (`MapId`, `Number`, `xPos`, `yPos`) VALUES ('101', '12', '553', '546');
INSERT INTO `locations` (`MapId`, `Number`, `xPos`, `yPos`) VALUES ('101', '13', '464', '448');
INSERT INTO `locations` (`MapId`, `Number`, `xPos`, `yPos`) VALUES ('101', '14', '480', '669');
INSERT INTO `locations` (`MapId`, `Number`, `xPos`, `yPos`) VALUES ('101', '15', '223', '547');
INSERT INTO `locations` (`MapId`, `Number`, `xPos`, `yPos`) VALUES ('101', '16', '105', '523');
INSERT INTO `locations` (`MapId`, `Number`, `xPos`, `yPos`) VALUES ('101', '17', '619', '683');
INSERT INTO `locations` (`MapId`, `Number`, `xPos`, `yPos`) VALUES ('101', '18', '604', '496');
INSERT INTO `locations` (`MapId`, `Number`, `xPos`, `yPos`) VALUES ('101', '19', '568', '310');
INSERT INTO `locations` (`MapId`, `Number`, `xPos`, `yPos`) VALUES ('101', '20', '407', '350');
INSERT INTO `locations` (`MapId`, `Number`, `xPos`, `yPos`) VALUES ('101', '21', '66', '339');
INSERT INTO `locations` (`MapId`, `Number`, `xPos`, `yPos`) VALUES ('101', '22', '177', '288');
INSERT INTO `locations` (`MapId`, `Number`, `xPos`, `yPos`) VALUES ('101', '23', '302', '286');
INSERT INTO `locations` (`MapId`, `Number`, `xPos`, `yPos`) VALUES ('101', '24', '393', '279');
INSERT INTO `locations` (`MapId`, `Number`, `xPos`, `yPos`) VALUES ('101', '25', '657', '179');
INSERT INTO `locations` (`MapId`, `Number`, `xPos`, `yPos`) VALUES ('101', '26', '551', '180');
INSERT INTO `locations` (`MapId`, `Number`, `xPos`, `yPos`) VALUES ('101', '27', '481', '144');
INSERT INTO `locations` (`MapId`, `Number`, `xPos`, `yPos`) VALUES ('101', '28', '674', '106');
INSERT INTO `locations` (`MapId`, `Number`, `xPos`, `yPos`) VALUES ('101', '29', '567', '89');
INSERT INTO `locations` (`MapId`, `Number`, `xPos`, `yPos`) VALUES ('101', '30', '372', '210');
INSERT INTO `locations` (`MapId`, `Number`, `xPos`, `yPos`) VALUES ('101', '31', '322', '80');
INSERT INTO `locations` (`MapId`, `Number`, `xPos`, `yPos`) VALUES ('101', '32', '213', '109');
INSERT INTO `locations` (`MapId`, `Number`, `xPos`, `yPos`) VALUES ('101', '33', '180', '177');
INSERT INTO `locations` (`MapId`, `Number`, `xPos`, `yPos`) VALUES ('101', '34', '70', '178');
INSERT INTO `locations` (`MapId`, `Number`, `xPos`, `yPos`) VALUES ('101', '35', '51', '119');
INSERT INTO `locations` (`MapId`, `Number`, `xPos`, `yPos`) VALUES ('101', '36', '606', '452');
INSERT INTO `locations` (`MapId`, `Number`, `xPos`, `yPos`) VALUES ('101', '37', '712', '445');
INSERT INTO `locations` (`MapId`, `Number`, `xPos`, `yPos`) VALUES ('101', '38', '277', '699');


-- 3. The connections between locations on the map.
--    NOTE: For Ticket type: 0 = Yellow; 1 = Purple; 2 = Red; 3 = Black.


INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '1', '8', '0');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '1', '21', '0');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '1', '22', '0');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '1', '23', '0');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '1', '34', '0');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '1', '35', '0');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '1', '24', '0');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '1', '26', '0');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '1', '29', '0');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '1', '28', '0');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '1', '19', '0');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '1', '20', '0');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '1', '37', '0');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '1', '36', '0');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '1', '7', '0');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '1', '15', '0');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '1', '2', '0');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '1', '14', '0');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '1', '11', '1');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '1', '13', '1');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '1', '2', '1');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '1', '9', '1');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '1', '6', '1');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '1', '16', '1');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '1', '23', '1');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '1', '12', '1');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '1', '36', '1');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '1', '33', '1');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '1', '34', '1');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '1', '31', '1');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '1', '29', '1');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '1', '27', '1');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '1', '30', '1');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '1', '25', '1');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '1', '38', '1');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '1', '4', '1');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '1', '5', '1');

INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '2', '15', '0');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '2', '14', '0');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '2', '4', '0');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '2', '7', '0');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '2', '10', '0');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '2', '1', '0');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '2', '38', '1');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '2', '4', '1');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '2', '5', '1');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '2', '11', '1');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '2', '13', '1');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '2', '12', '1');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '2', '36', '1');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '2', '25', '1');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '2', '29', '1');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '2', '27', '1');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '2', '30', '1');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '2', '31', '1');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '2', '32', '1');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '2', '33', '1');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '2', '34', '1');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '2', '23', '1');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '2', '9', '1');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '2', '4', '2');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '2', '5', '2');

INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '3', '14', '2');

INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '4', '15', '0');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '4', '14', '0');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '4', '7', '0');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '4', '10', '0');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '4', '8', '0');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '4', '21', '0');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '4', '23', '0');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '4', '34', '0');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '4', '35', '0');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '4', '24', '0');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '4', '26', '0');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '4', '28', '0');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '4', '29', '0');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '4', '30', '0');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '4', '19', '0');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '4', '37', '0');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '4', '36', '0');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '4', '20', '0');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '4', '5', '1');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '4', '38', '1');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '4', '11', '1');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '4', '12', '1');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '4', '13', '1');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '4', '36', '1');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '4', '9', '1');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '4', '21', '1');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '4', '10', '1');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '4', '25', '1');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '4', '27', '1');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '4', '29', '1');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '4', '30', '1');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '4', '31', '1');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '4', '32', '1');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '4', '33', '1');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '4', '34', '1');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '4', '35', '1');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '4', '23', '1');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '4', '5', '2');

INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '5', '6', '0');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '5', '38', '1');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '5', '9', '1');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '5', '23', '1');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '5', '33', '1');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '5', '32', '1');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '5', '31', '1');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '5', '34', '1');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '5', '29', '1');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '5', '27', '1');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '5', '25', '1');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '5', '11', '1');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '5', '12', '1');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '5', '13', '1');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '5', '36', '1');

INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '6', '16', '1');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '6', '9', '1');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '6', '11', '1');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '6', '12', '1');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '6', '13', '1');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '6', '36', '1');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '6', '23', '1');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '6', '25', '1');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '6', '26', '1');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '6', '27', '1');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '6', '29', '1');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '6', '30', '1');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '6', '31', '1');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '6', '32', '1');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '6', '33', '1');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '6', '34', '1');

INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '7', '15', '0');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '7', '14', '0');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '7', '10', '0');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '7', '8', '0');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '7', '21', '0');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '7', '22', '0');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '7', '23', '0');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '7', '24', '0');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '7', '34', '0');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '7', '35', '0');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '7', '26', '0');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '7', '29', '0');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '7', '30', '0');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '7', '28', '0');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '7', '19', '0');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '7', '37', '0');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '7', '36', '0');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '7', '20', '0');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '7', '19', '0');

INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '8', '10', '0');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '8', '22', '0');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '8', '23', '0');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '8', '24', '0');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '8', '34', '0');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '8', '35', '0');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '8', '26', '0');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '8', '29', '0');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '8', '30', '0');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '8', '28', '0');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '8', '19', '0');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '8', '37', '0');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '8', '36', '0');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '8', '20', '0');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '8', '21', '2');

INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '9', '16', '1');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '9', '11', '1');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '9', '12', '1');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '9', '13', '1');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '9', '36', '1');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '9', '23', '1');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '9', '25', '1');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '9', '29', '1');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '9', '31', '1');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '9', '27', '1');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '9', '30', '1');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '9', '31', '1');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '9', '32', '1');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '9', '33', '1');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '9', '34', '1');

INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '10', '15', '0');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '10', '14', '0');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '10', '21', '0');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '10', '22', '0');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '10', '23', '0');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '10', '24', '0');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '10', '26', '0');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '10', '28', '0');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '10', '29', '0');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '10', '19', '0');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '10', '34', '0');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '10', '35', '0');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '10', '20', '0');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '10', '37', '0');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '10', '36', '0');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '10', '21', '1');

INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '11', '13', '1');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '11', '12', '1');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '11', '36', '1');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '11', '25', '1');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '11', '27', '1');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '11', '30', '1');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '11', '31', '1');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '11', '32', '1');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '11', '33', '1');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '11', '34', '1');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '11', '38', '1');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '11', '19', '2');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '11', '26', '2');

INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '12', '13', '1');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '12', '36', '1');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '12', '38', '1');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '12', '23', '1');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '12', '25', '1');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '12', '29', '1');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '12', '31', '1');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '12', '32', '1');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '12', '33', '1');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '12', '34', '1');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '12', '16', '1');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '12', '13', '2');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '12', '36', '2');

INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '13', '36', '1');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '13', '38', '1');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '13', '16', '1');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '13', '23', '1');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '13', '25', '1');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '13', '29', '1');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '13', '27', '1');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '13', '30', '1');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '13', '31', '1');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '13', '32', '1');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '13', '33', '1');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '13', '34', '1');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '13', '36', '2');

INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '14', '15', '0');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '14', '21', '0');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '14', '22', '0');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '14', '23', '0');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '14', '24', '0');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '14', '26', '0');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '14', '28', '0');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '14', '29', '0');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '14', '30', '0');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '14', '19', '0');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '14', '37', '0');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '14', '36', '0');

INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '15', '21', '0');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '15', '22', '0');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '15', '23', '0');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '15', '24', '0');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '15', '20', '0');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '15', '19', '0');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '15', '37', '0');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '15', '36', '0');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '15', '28', '0');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '15', '29', '0');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '15', '30', '0');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '15', '34', '0');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '15', '35', '0');

INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '16', '38', '1');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '16', '30', '1');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '16', '31', '1');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '16', '29', '1');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '16', '27', '1');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '16', '25', '1');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '16', '32', '1');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '16', '33', '1');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '16', '34', '1');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '16', '23', '1');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '16', '36', '1');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '16', '38', '1');

INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '17', '18', '0');

INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '19', '37', '0');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '19', '36', '0');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '19', '20', '0');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '19', '26', '0');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '19', '29', '0');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '19', '28', '0');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '19', '30', '0');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '19', '24', '0');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '19', '23', '0');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '19', '22', '0');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '19', '34', '0');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '19', '21', '0');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '19', '35', '0');

INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '20', '37', '0');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '20', '36', '0');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '20', '28', '0');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '20', '26', '0');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '20', '29', '0');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '20', '30', '0');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '20', '24', '0');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '20', '23', '0');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '20', '22', '0');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '20', '21', '0');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '20', '34', '0');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '20', '35', '0');

INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '21', '22', '0');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '21', '23', '0');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '21', '24', '0');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '21', '25', '0');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '21', '26', '0');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '21', '28', '0');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '21', '29', '0');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '21', '30', '0');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '21', '34', '0');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '21', '35', '0');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '21', '36', '0');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '21', '37', '0');

INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '22', '23', '0');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '22', '24', '0');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '22', '26', '0');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '22', '28', '0');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '22', '29', '0');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '22', '30', '0');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '22', '34', '0');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '22', '35', '0');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '22', '36', '0');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '22', '37', '0');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '22', '35', '2');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '22', '24', '2');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '22', '30', '2');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '22', '31', '2');

INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '23', '24', '0');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '23', '34', '0');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '23', '35', '0');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '23', '26', '0');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '23', '29', '0');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '23', '28', '0');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '23', '37', '0');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '23', '36', '0');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '23', '30', '0');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '23', '36', '1');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '23', '25', '1');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '23', '27', '1');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '23', '29', '1');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '23', '30', '1');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '23', '31', '1');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '23', '32', '1');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '23', '33', '1');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '23', '34', '1');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '23', '38', '1');

INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '24', '26', '0');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '24', '28', '0');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '24', '29', '0');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '24', '30', '0');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '24', '34', '0');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '24', '35', '0');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '24', '36', '0');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '24', '37', '0');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '24', '30', '1');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '24', '31', '1');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '24', '35', '1');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '24', '25', '1');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '24', '27', '1');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '24', '29', '1');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '24', '32', '1');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '24', '33', '1');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '24', '34', '1');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '24', '36', '1');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '24', '38', '1');

INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '25', '27', '1');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '25', '29', '1');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '25', '30', '1');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '25', '31', '1');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '25', '32', '1');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '25', '33', '1');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '25', '34', '1');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '25', '38', '1');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '25', '28', '2');


INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '26', '28', '0');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '26', '29', '0');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '26', '30', '0');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '26', '34', '0');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '26', '35', '0');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '26', '36', '0');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '26', '37', '0');

INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '27', '29', '1');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '27', '30', '1');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '27', '31', '1');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '27', '32', '1');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '27', '33', '1');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '27', '34', '1');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '27', '36', '1');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '27', '38', '1');

INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '28', '29', '0');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '28', '30', '0');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '28', '34', '0');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '28', '35', '0');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '28', '36', '0');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '28', '37', '0');

INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '29', '30', '0');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '29', '31', '0');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '29', '37', '0');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '29', '36', '0');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '29', '34', '0');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '29', '35', '0');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '29', '30', '1');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '29', '31', '1');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '29', '32', '1');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '29', '33', '1');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '29', '34', '1');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '29', '36', '1');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '29', '38', '1');

INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '30', '34', '0');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '30', '35', '0');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '30', '36', '0');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '30', '37', '0');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '30', '31', '1');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '30', '32', '1');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '30', '33', '1');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '30', '34', '1');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '30', '36', '1');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '30', '38', '1');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '30', '31', '2');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '30', '35', '2');

INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '31', '32', '1');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '31', '33', '1');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '31', '34', '1');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '31', '36', '1');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '31', '38', '1');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '31', '35', '2');

INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '32', '33', '1');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '32', '34', '1');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '32', '36', '1');

INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '33', '34', '1');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '33', '36', '1');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '33', '38', '1');

INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '34', '35', '0');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '34', '36', '0');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '34', '37', '0');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '34', '36', '0');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '34', '38', '0');

INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '35', '36', '0');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '35', '37', '0');

INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '36', '37', '0');
INSERT INTO `connections` (`MapId`, `A`, `B`, `Ticket`) VALUES ('101', '36', '38', '1');



-- 4. The starting positions
--    NOTE: For Role type: 1 = Fugitive; 2 = Detective

INSERT INTO `startlocations` (`MapId`, `Role`, `Location`) VALUES ('101', '1', '12');
INSERT INTO `startlocations` (`MapId`, `Role`, `Location`) VALUES ('101', '2', '22');
INSERT INTO `startlocations` (`MapId`, `Role`, `Location`) VALUES ('101', '2', '16');
INSERT INTO `startlocations` (`MapId`, `Role`, `Location`) VALUES ('101', '2', '27');
INSERT INTO `startlocations` (`MapId`, `Role`, `Location`) VALUES ('101', '2', '37');
